# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-07 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0235_userprofile_desktop_icon_count_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmessage',
            name='reply_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_message',
            field=models.TextField(null=True),
        ),
    ]
