# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-07 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0236_auto_20190807_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedmessage',
            name='reply_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_message',
        ),
        migrations.AddField(
            model_name='archivedmessage',
            name='reply_message_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_message_id',
            field=models.IntegerField(null=True),
        ),
    ]
